-- Insert categories into the Category table
INSERT INTO Category (name, slug, description) VALUES
('Assisted Living Facility', 'assisted-living-facility', 'Assisted living facilities provide a supportive environment for seniors who need help with daily activities such as bathing, dressing, and medication management. These communities offer personalized care, social activities, and a safe, home-like atmosphere.'),
('Retirement Home', 'retirement-home', 'Retirement homes are designed for seniors who wish to live independently while having access to a range of amenities and social opportunities. These homes offer a vibrant community lifestyle with activities, dining, and on-site healthcare services.'),
('Retirement Community', 'retirement-community', 'Retirement communities offer an all-inclusive lifestyle for active seniors, featuring a range of housing options, recreational activities, and healthcare services. These communities are ideal for retirees seeking a dynamic and engaging environment.'),
('Nursing Home', 'nursing-home', 'Nursing homes provide comprehensive medical care and assistance for seniors with chronic illnesses or disabilities. These facilities offer skilled nursing care, rehabilitation services, and a secure environment for residents requiring constant supervision.'),
('Group Home', 'group-home', 'Group homes offer a family-like setting for seniors who need assistance with daily living activities. These homes provide personalized care, companionship, and a nurturing environment for small groups of residents.'),
('Senior Citizen Center', 'senior-citizen-center', 'Senior citizen centers are community hubs that offer recreational, educational, and social activities for older adults. These centers provide a welcoming space for seniors to stay active, engaged, and connected with their peers.'),
('Hospice', 'hospice', 'Hospice care focuses on providing comfort and support for terminally ill patients and their families. These services include pain management, emotional support, and compassionate care to ensure dignity and quality of life during the end-of-life journey.'),
('Rehabilitation Center', 'rehabilitation-center', 'Rehabilitation centers offer specialized therapies and treatments for seniors recovering from surgeries, illnesses, or injuries. These facilities provide physical, occupational, and speech therapy to help patients regain their independence and improve their quality of life.'),
('Day Care Center', 'day-care-center', 'Senior day care centers provide daytime care and activities for older adults, offering a safe and stimulating environment. These centers offer social interaction, meals, and health monitoring while allowing caregivers respite during the day.'),
('Community Center', 'community-center', 'Community centers offer a wide range of activities and services for seniors, including fitness classes, educational programs, and social events. These centers serve as gathering places for older adults to connect, learn, and stay active.'),
('Memory Care Facility', 'memory-care-facility', 'Memory care facilities specialize in providing care for seniors with Alzheimer\'s disease and other forms of dementia. These communities offer structured environments, specialized programs, and trained staff to ensure safety and enhance quality of life.'),
('Independent Living Community', 'independent-living-community', 'Independent living communities cater to active seniors who are looking for a hassle-free lifestyle without the responsibilities of homeownership. These communities offer various amenities, social activities, and maintenance-free living.'),
('Continuing Care Retirement Community', 'continuing-care-retirement-community', 'Continuing care retirement communities (CCRCs) provide a range of living options, from independent living to skilled nursing care, all within one community. CCRCs offer a continuum of care, allowing residents to age in place as their needs change.'),
('Respite Care', 'respite-care', 'Respite care services provide temporary relief for caregivers by offering short-term stays for seniors in assisted living or nursing home settings. These services ensure that seniors receive quality care while caregivers take a needed break.'),
('Home Health Care Service', 'home-health-care-service', 'Home health care services provide medical and non-medical support for seniors in the comfort of their own homes. Services include skilled nursing, physical therapy, personal care, and assistance with daily activities.'),
('Adult Day Health Center', 'adult-day-health-center', 'Adult day health centers offer medical and therapeutic services for seniors during the day, including health monitoring, rehabilitation therapies, and social activities. These centers provide comprehensive care while allowing seniors to return home in the evening.');