import { appendFileSync } from 'fs';
import { config } from 'dotenv';
import fetch from 'node-fetch';

config(); // Load environment variables from .env file

const urls = [
    "https://agingresidence.com/community/edelweiss-assisted-living/",
    "https://agingresidence.com/community/golden-years-assisted-living/",
    "https://agingresidence.com/community/glencroft-senior-living/",
    "https://agingresidence.com/community/tanner-terrace-apartments/",
    "https://agingresidence.com/community/glencroft-center-for-modern-aging/",
    "https://agingresidence.com/community/holiday-westgate-village/",
    "https://agingresidence.com/community/glendale-enterprise-lofts/",
    "https://agingresidence.com/community/manistee-manor-retirement-living-disciples-house-of-glendale-inc/",
    "https://agingresidence.com/community/quail-manor-assisted-living/",
    "https://agingresidence.com/community/beverly-assisted-living/",
    "https://agingresidence.com/community/brookdale-arrowhead-ranch/",
    "https://agingresidence.com/community/ozark-senior-citizen-housing/",
    "https://agingresidence.com/community/magnolia-square-nursing/",
    "https://agingresidence.com/community/christian-health-care-of-springfield-east/",
    "https://agingresidence.com/community/nixa-nursing-rehab/",
    "https://agingresidence.com/community/bristol-manor/",
    "https://agingresidence.com/community/ozard-residential-care-center/",
    "https://agingresidence.com/community/ozark-nursing-care-center/",
    "https://agingresidence.com/community/ozark-riverview-manor/",
    "https://agingresidence.com/community/holiday-creekside-at-shallowford/",
    "https://agingresidence.com/community/brookdale-hixson/",
    "https://agingresidence.com/community/rockbridge-oaks/",
    "https://agingresidence.com/community/storypoint-chattanooga/",
    "https://agingresidence.com/community/the-rosewood-at-fort-oglethorpe/",
    "https://agingresidence.com/community/care-first-assisted-living-home-llc/",
    "https://agingresidence.com/community/bella-amore-assisted-living/",
    "https://agingresidence.com/community/apollo-residential-assisted-living/",
    "https://agingresidence.com/community/christian-care-health-center/",
    "https://agingresidence.com/community/haven-health-phoenix/",
    "https://agingresidence.com/community/heritage-court-post-acute-of-scottsdale/",
    "https://agingresidence.com/community/la-loma-village-health-rehabilitation-center/",
    "https://agingresidence.com/community/mcdowell-village/",
    "https://agingresidence.com/community/ocotillo-place/",
    "https://agingresidence.com/community/mimosa-springs-assisted-living/",
    "https://agingresidence.com/community/legacy-village-of-salt-river/",
    "https://agingresidence.com/community/north-scottsdale-retreat/",
    "https://agingresidence.com/community/the-springs-of-scottsdale-independent-assisted-senior-living/",
    "https://agingresidence.com/community/senior-living-services/",
    "https://agingresidence.com/community/sunrise-care-homes-shea/",
    "https://agingresidence.com/community/pinnacle-peak-assisted-living/",
    "https://agingresidence.com/community/belmont-village-senior-living-scottsdale/",
    "https://agingresidence.com/community/central-scottsdale-assisted-living-by-md-senior-living/",
    "https://agingresidence.com/community/sunrise-of-scottsdale/",
    "https://agingresidence.com/community/desert-cove-assisted-living/",
    "https://agingresidence.com/community/sun-valley-manor-assisted-living-home/",
    "https://agingresidence.com/community/clarendale-of-chandler/",
    "https://agingresidence.com/community/plaza-view-assisted-living/",
    "https://agingresidence.com/community/bridgewater-assisted-living-midtown/",
    "https://agingresidence.com/community/ridge-at-the-stratford/",
    "https://agingresidence.com/community/paradise-valley-senior-home-care/",
    "https://agingresidence.com/community/golden-eagleassistedliving-home/",
    "https://agingresidence.com/community/north-haven-assisted-living/",
    "https://agingresidence.com/community/madison-gardens-senior-community/",
    "https://agingresidence.com/community/tina-loring-group-home-tlgh/",
    "https://agingresidence.com/community/all-assisted-living/",
    "https://agingresidence.com/community/desert-haven-llc/",
    "https://agingresidence.com/community/desert-haven-home-care/",
    "https://agingresidence.com/community/ambiance-assisted-living-home/",
    "https://agingresidence.com/community/primavera-assisted-living-llc/",
    "https://agingresidence.com/community/heritage-at-carefree-assisted-living/",
    "https://agingresidence.com/community/the-senior-living-institute/",
    "https://agingresidence.com/community/carefree-manor-assisted-living/",
    "https://agingresidence.com/community/proposed-assisted-living-site/",
    "https://agingresidence.com/community/via-linda-assisted-living/",
    "https://agingresidence.com/community/scottsdale-village-square/",
    "https://agingresidence.com/community/promenade-at-beatitudes-campus/",
    "https://agingresidence.com/community/pueblo-norte-senior-living/",
    "https://agingresidence.com/community/acoya-shea/",
    "https://agingresidence.com/community/north-valley-senior-living/",
    "https://agingresidence.com/community/olive-grove-assisted-living-and-memory-care/",
    "https://agingresidence.com/community/rose-court-senior-living/",
    "https://agingresidence.com/community/matters-of-senior-living-inc/",
    "https://agingresidence.com/community/vista-living-senior-care-camelback/",
    "https://agingresidence.com/community/olive-ridge-senior-living/",
    "https://agingresidence.com/community/fletcher-heights-assisted-living/",
    "https://agingresidence.com/community/fellowship-towers/",
    "https://agingresidence.com/community/the-retreat-at-alameda-assisted-living-memory-care/",
    "https://agingresidence.com/community/white-violet-assisted-living/",
    "https://agingresidence.com/community/the-park-at-surprise-independent-living-community/",
    "https://agingresidence.com/community/browns-assisted-living-center/",
    "https://agingresidence.com/community/harmony-of-stevens-point/",
    "https://agingresidence.com/community/care-partners-assisted-living/",
    "https://agingresidence.com/community/sylvan-crossings-of-stevens-point/",
    "https://agingresidence.com/community/copperleaf-senior-living/",
    "https://agingresidence.com/community/a-sunny-pine-assisted-living-community/",
    "https://agingresidence.com/community/zen-senior-living/",
    "https://agingresidence.com/community/acoma-assisted-living/",
    "https://agingresidence.com/community/encanto-palms-assisted-living/",
    "https://agingresidence.com/community/hawthorn-court-at-ahwatukee/",
    "https://agingresidence.com/community/ahwatukee-manor-assisted-living-llc/",
    "https://agingresidence.com/community/clearwater-ahwatukee/",
    "https://agingresidence.com/community/south-mountain-care-center/",
    "https://agingresidence.com/community/st-joseph-home-for-the-elderly/",
    "https://agingresidence.com/community/ahwatukee-adult-care-ii/",
    "https://agingresidence.com/community/bridgewater-assisted-living-deer-valley/",
    "https://agingresidence.com/community/desert-comfort-assisted-living-home/",
    "https://agingresidence.com/community/affection-care-assisted-living/",
    "https://agingresidence.com/community/sunnyslope-manor/",
    "https://agingresidence.com/community/clearwater-mayo-blvd/",
    "https://agingresidence.com/community/the-ranch-estates-at-scottsdale/",
    "https://agingresidence.com/community/maravilla-scottsdale/",
    "https://agingresidence.com/community/az-life-assisted-living-home/",
    "https://agingresidence.com/community/ventana-winds-retirement-home/",
    "https://agingresidence.com/community/redfield-assisted-living-llc/",
    "https://agingresidence.com/community/lifestyles-of-glendale/",
    "https://agingresidence.com/community/thunderbird-senior-living/",
    "https://agingresidence.com/community/baptist-homes-of-ozark/",
    "https://agingresidence.com/community/hopedale-cottage/",
    "https://agingresidence.com/community/century-pines-assisted-living/",
    "https://agingresidence.com/community/lookout-mountain-assisted-living/",
    "https://agingresidence.com/community/blue-sage-assisted-living-moon-valley/",
    "https://agingresidence.com/community/lovin-touch-assisted-living/",
    "https://agingresidence.com/community/desert-terrace-healthcare-center/",
    "https://agingresidence.com/community/desert-haven-care-center/",
    "https://agingresidence.com/community/maryland-gardens-post-acute/",
    "https://agingresidence.com/community/the-gardens-of-scottsdale/",
    "https://agingresidence.com/community/brookdale-north-scottsdale/",
    "https://agingresidence.com/community/assisted-living-of-scottsdale/",
    "https://agingresidence.com/community/senior-valley-assisted-living/",
    "https://agingresidence.com/community/manor-on-paradise-assisted-senior-living/",
    "https://agingresidence.com/community/sunnyside-assisted-living-home/",
    "https://agingresidence.com/community/shadow-mountain-memory-care/",
    "https://agingresidence.com/community/great-heart-adult-assisted-living-home/",
    "https://agingresidence.com/community/central-assisted-living-llc/",
    "https://agingresidence.com/community/biltmore-assisted-living/",
    "https://agingresidence.com/community/bella-vita-assisted-living-at-cholla/",
    "https://agingresidence.com/community/clarendale-arcadia/",
    "https://agingresidence.com/community/beatitudes-campus/",
    "https://agingresidence.com/community/morningstar-assisted-living-memory-care-at-arcadia/",
    "https://agingresidence.com/community/paradise-valley-senior-retreat/",
    "https://agingresidence.com/community/paradise-valley-foothills-assisted-living/",
    "https://agingresidence.com/community/holiday-madison-meadows/",
    "https://agingresidence.com/community/lynettes-care-home/",
    "https://agingresidence.com/community/joyful-haven-assisted-living-home-llc/",
    "https://agingresidence.com/community/abundant-life-senior-care-llc/",
    "https://agingresidence.com/community/senior-living-cave-creek-az/",
    "https://agingresidence.com/community/pacifica-senior-living-paradise-valley/",
    "https://agingresidence.com/community/avista-senior-living-north-mountain/",
    "https://agingresidence.com/community/fellowship-square-phoenix/",
    "https://agingresidence.com/community/park-terrace-senior-living/",
    "https://agingresidence.com/community/willow-brooke-point-senior-living/",
    "https://agingresidence.com/community/la-siena/",
    "https://agingresidence.com/community/mountain-park-senior-living/",
    "https://agingresidence.com/community/brookdale-desert-ridge/",
    "https://agingresidence.com/community/the-manor-village-at-desert-ridge/",
    "https://agingresidence.com/community/lifestream-at-youngtown/",
    "https://agingresidence.com/community/lifestream-at-glendale/",
    "https://agingresidence.com/community/north-valley-assisted-living/",
    "https://agingresidence.com/community/bethesda-gardens-assisted-living-and-memory-care-phoenix/",
    "https://agingresidence.com/community/senior-paradise-living/",
    "https://agingresidence.com/community/infinite-pathways-care-home-memory-care/",
    "https://agingresidence.com/community/brookdale-central-paradise-valley/",
    "https://agingresidence.com/community/lifestream-at-north-phoenix/",
    "https://agingresidence.com/all-categories-2/",
    "https://agingresidence.com/all-locations-2/",
    "https://agingresidence.com/terms-and-conditions-2/",
    "https://agingresidence.com/privacy-policy-3/",
    "https://agingresidence.com/search-home/",
    "https://agingresidence.com/search-result/",
    "https://agingresidence.com/add-listing/",
    "https://agingresidence.com/all-listings/",
    "https://agingresidence.com/single-category/",
    "https://agingresidence.com/single-location/",
    "https://agingresidence.com/single-tag/",
    "https://agingresidence.com/author-profile/",
    "https://agingresidence.com/dashboard/",
    "https://agingresidence.com/registration/",
    "https://agingresidence.com/login/",
    "https://agingresidence.com/",
    "https://agingresidence.com/payment-receipt/",
    "https://agingresidence.com/transaction-failure/",
    "https://agingresidence.com/checkout/",
    "https://agingresidence.com/all-categories/",
    "https://agingresidence.com/all-locations/",
    "https://agingresidence.com/all-authors/",
    "https://agingresidence.com/terms-and-conditions/",
    "https://agingresidence.com/privacy-policy-2/",
    "https://agingresidence.com/search-home-2/",
    "https://agingresidence.com/search-result-2/",
    "https://agingresidence.com/add-listing-2/",
    "https://agingresidence.com/all-listings-2/",
    "https://agingresidence.com/single-category-2/",
    "https://agingresidence.com/single-location-2/",
    "https://agingresidence.com/single-tag-2/",
    "https://agingresidence.com/author-profile-2/",
    "https://agingresidence.com/dashboard-2/",
    "https://agingresidence.com/registration-2/",
    "https://agingresidence.com/login-2/"
];

// Check each URL and log 404 responses
const checkUrls = async () => {
    const baseUrl = process.env.BASE_URL || 'https://agingresidence.vercel.app';
    const logFile = '404-logs.txt';

    for (const url of urls) {
        const newUrl = url.replace('https://agingresidence.com', baseUrl);
        try {
            const response = await fetch(newUrl);
            if (response.status === 404) {
                fs.appendFileSync(logFile, `${newUrl}\n`);
                console.log(`404 Not Found: ${newUrl}`);
            } else {
                console.log(`200 OK: ${newUrl}`);
            }
        } catch (error) {
            console.error(`Error fetching ${newUrl}: ${error.message}`);
        }
    }
};

checkUrls();
